services:
  collector:
    build:
      context: ./collector
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://pstgr_user:pstgr_pass@codewars_db:5432/codewars_db
    depends_on:
      codewars_db:
        condition: service_healthy
  analyzer:
    build:
      context: ./analyzer
    ports:
      - 5001:5001
  display:
    build:
      context: ./display
    ports:
      - 3000:3000
  codewars_db:
    build: ./db
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=pstgr_user
      - POSTGRES_PASSWORD=pstgr_pass
      - POSTGRES_DB=codewars_db
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5