version: '3'
services:
  collector:
    build:
      context: ./collector
    ports:
      - 5000:5000
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    depends_on:
      db:
        condition: service_healthy
  analyzer:
    build:
      context: ./analyzer
    ports:
      - 5001:5001
    depends_on:
      - rabbitmq
  display:
    build:
      context: ./display
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=codewars_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt