version: '3'

services:
  database:
    build:
      context: ./database
    ports:
      - 5000:5000
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    depends_on:
      - rabbitmq
      - postgres

  analyzer:
    build:
      context: ./analyzer
    ports:
      - 5001:5001
    restart: unless-stopped
    volumes: ['./analyzer:/app']
    depends_on:
      - rabbitmq

  display:
    build:
      context: ./display
    ports:
      - 3000:3000
    restart: unless-stopped

  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: codewars_db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD_FILE: pswd
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: "rabbitmq:3.9-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres_data: